# yml 中 空格的数量绝对不要打乱，也就是每行的缩进要按照规则走
spring:
  datasource:
    url: jdbc:mysql://192.168.116.1:3306/youlexuandb?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.116.200
    port: 6379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
    timeout: 3000
server:
  port: 8080

swagger:
  enable: true